main:
  push:
    - services:
        - docker
      docker:
        image: docker:24.0.9
      stages:
        - name: docker-build-main
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export TAG="${CNB_BRANCH_SLUG}-${CNB_SHORT_SHA}"
            - docker build -f ./Dockerfile -t "${IMAGE}:${TAG}" -t "${IMAGE}:main-latest" .
        - name: docker-push-main
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export TAG="${CNB_BRANCH_SLUG}-${CNB_SHORT_SHA}"
            - docker push "${IMAGE}:${TAG}"
            - docker push "${IMAGE}:main-latest"

production:
  push:
    - services:
        - docker
      docker:
        image: docker:24.0.9
      stages:
        - name: docker-build-production
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export TAG="${CNB_BRANCH_SLUG}-${CNB_SHORT_SHA}"
            - docker build -f ./Dockerfile -t "${IMAGE}:${TAG}" -t "${IMAGE}:production-latest" -t "${IMAGE}:latest" .
        - name: docker-push-production
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export TAG="${CNB_BRANCH_SLUG}-${CNB_SHORT_SHA}"
            - docker push "${IMAGE}:${TAG}"
            - docker push "${IMAGE}:production-latest"
            - docker push "${IMAGE}:latest"
