production:
  push:
    - services:
        - docker
      docker:
        image: docker:24.0.9
      stages:
        - name: docker-build-versioned
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export VERSION_TAG="$(tr -d '\r\n' < VERSION)"
            - if [ -z "${VERSION_TAG}" ]; then export VERSION_TAG="${CNB_COMMIT_SHORT:-nosha}"; fi
            - docker build -f ./Dockerfile --build-arg COMMIT_SHA="${CNB_COMMIT_SHORT:-nosha}" -t "${IMAGE}:${VERSION_TAG}" .
        - name: docker-push-versioned
          script:
            - export IMAGE="${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}"
            - export VERSION_TAG="$(tr -d '\r\n' < VERSION)"
            - if [ -z "${VERSION_TAG}" ]; then export VERSION_TAG="${CNB_COMMIT_SHORT:-nosha}"; fi
            - docker push "${IMAGE}:${VERSION_TAG}"
